name: flutter_realworld_app
description: Exemplary real world application built with Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  validators: ^1.0.0+1
  flutter_redurx: ^0.4.3
  built_value: ^6.1.6
  built_collection: ^4.0.0
  cupertino_icons: ^0.1.2
  dio: ^1.0.9
  shared_preferences: ^0.4.3
  cached_network_image: ^0.5.1
  tuple: ^1.0.2
  flushbar: ^1.2.0


dev_dependencies:
  test: ^1.5.1
  flutter_test:
    sdk: flutter
  built_value_generator: ^6.1.6
  build_runner: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - res/assets/smiley-cyrus.jpg

